import { useEffect, useState } from 'react';
import { getDashboard } from '../services/api';
import { getWalkingStats } from '../services/api';
import { Link } from 'react-router-dom';

export default function EmployeeDashboard() {
  const [dash, setDash] = useState(null);
  const [walk, setWalk] = useState(null);

  useEffect(() => {
    async function load() {
      try {
        const d = await getDashboard('me');
        setDash(d);
      } catch {
        setDash(null);
      }
      try {
        const w = await getWalkingStats();
        setWalk(w);
      } catch {
        setWalk(null);
      }
    }
    load();
  }, []);

  return (
    <div className="min-h-screen pt-24 px-4 md:px-8">
      <div className="max-w-6xl mx-auto space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Employee Dashboard</h1>
            <p className="text-sm text-gray-400">Overview of your sustainability impact and progress.</p>
          </div>
          <div className="space-x-2">
            <Link to="/upload-proof" className="btn-primary">Upload Proof</Link>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="card p-4">
            <div className="text-sm text-gray-400">Green Impact Score</div>
            <div className="text-3xl font-bold">{dash?.sustainability_score ?? '--'}</div>
          </div>
          <div className="card p-4">
            <div className="text-sm text-gray-400">Carbon Confidence</div>
            <div className="text-3xl font-bold">{dash?.carbon_confidence ?? '--'}%</div>
          </div>
          <div className="card p-4">
            <div className="text-sm text-gray-400">Green Points</div>
            <div className="text-3xl font-bold">{dash?.eco_points ?? '--'}</div>
          </div>
          <div className="card p-4">
            <div className="text-sm text-gray-400">Sustainability Grade</div>
            <div className="text-3xl font-bold">{dash?.grade ?? '--'}</div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="card p-4 lg:col-span-2">
            <h3 className="font-semibold mb-2">Walking Progress</h3>
            <div className="text-sm text-gray-400 mb-4">Steps, distance and carbon saved.</div>
            <div className="space-y-2">
              <div className="flex justify-between"><span>Total Steps</span><strong>{walk?.total_steps ?? '--'}</strong></div>
              <div className="flex justify-between"><span>Distance</span><strong>{walk?.total_distance_km ?? '--'} km</strong></div>
              <div className="flex justify-between"><span>Total Carbon Saved</span><strong>{walk?.total_carbon_saved_kg ?? '--'} kg</strong></div>
              <div className="flex justify-between"><span>Walking Streak</span><strong>{walk?.walking_streak_days ?? 0} days</strong></div>
            </div>
          </div>

          <div className="card p-4">
            <h3 className="font-semibold mb-2">Badges & Achievements</h3>
            <div className="text-sm text-gray-400">View badges earned and progress towards next badge.</div>
            <div className="mt-4">
              <Link to="/rewards" className="text-primary-400">View Rewards & Badges</Link>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="card p-4 lg:col-span-2">
            <h3 className="font-semibold mb-2">Campaign Participation</h3>
            <p className="text-sm text-gray-400">Active campaigns and your position.</p>
            <div className="mt-4 text-sm text-gray-300">Open the Campaigns page to join and view leaderboards.</div>
          </div>
          <div className="card p-4">
            <h3 className="font-semibold mb-2">Recent Uploads</h3>
            <p className="text-sm text-gray-400">Latest proofs you uploaded.</p>
          </div>
        </div>

        <div className="card p-4">
          <h3 className="font-semibold mb-2">AI Sustainability Insights</h3>
          <p className="text-sm text-gray-400">Contextual tips generated by our AI coach.</p>
          <div className="mt-3 text-sm text-gray-300">You walked more this week — great job reducing short car trips!</div>
        </div>
      </div>
    </div>
  );
}
